_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/resnet18_w32a32.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN-ReLU"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (240000, 320000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/faster_rcnn/R_18_1x-FPN_SyncBN-bs4"
