_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "output/faster_rcnn/R_18_1x-FPN_SyncBN/model_final-export.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN-ReLU"
  RPN:
    HEAD_NORM: "SyncBN"
  ROI_BOX_HEAD:
    NORM: "SyncBN"
  QUANTIZATION:
    #policy: "configs/COCO-Detection/policy-faster-rcnn-r18.txt"
    scope: [
            'backbone.bottom_up.res2',
            'backbone.bottom_up.res3',
            'backbone.bottom_up.res4',
            'backbone.bottom_up.res5',
            # continue for more branch
            # FPN
            'backbone.fpn_lateral2',
            'backbone.fpn_output2',
            'backbone.fpn_lateral3',
            'backbone.fpn_output3',
            'backbone.fpn_lateral4',
            'backbone.fpn_output4',
            'backbone.fpn_lateral5',
            'backbone.fpn_output5',
            # Head
            'proposal_generator.rpn_head',
            'roi_heads.box_head',
           ]
    keyword: ["debug", "dorefa", "lsq"]
    fm_enable: True 
    wt_enable: True 
    padding_after_quant: True
    fm_bit: 1.0
    wt_bit: 1.0
    fm_boundary: 1.0
    wt_boundary: 1.0
    wt_quant_group: 1
    wt_adaptive: "var-mean"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (240000, 320000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/faster_rcnn/R_18_1x-FPN_SyncBN-lsq-bin-bs4-linear_rpn_output"
