_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet50/official-r50.pth.raw"
  #PIXEL_MEAN: [104.0, 116.0, 124.0]
  RESNETS:
    DEPTH: 50
    RES2_OUT_CHANNELS: 256
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  RETINANET:
    NORM: "SyncBN"
  QUANTIZATION:
    scope: [
            # backbone
            'backbone.bottom_up.res2',
            'backbone.bottom_up.res3',
            'backbone.bottom_up.res4',
            'backbone.bottom_up.res5',
            # FPN
            'backbone.fpn_lateral3',
            'backbone.fpn_output3',
            'backbone.fpn_lateral4',
            'backbone.fpn_output4',
            'backbone.fpn_lateral5',
            'backbone.fpn_output5',
            'backbone.top_block',
            # Head
            'head',
           ]
    keyword: ["debug", "dorefa", "lsq"]
    fm_enable: True 
    wt_enable: True 
    padding_after_quant: True
    fm_bit: 2.0
    wt_bit: 2.0
    fm_boundary: 1.0
    wt_boundary: 1.0
    wt_quant_group: 1
    wt_adaptive: "var-mean"
SOLVER:
  BASE_LR: 0.001  # decrease by 10
OUTPUT_DIR: output/coco-detection/retinanet_R_50_FPN_1x-Full_SyncBN-lsq-2bit
