_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet50/official-r50.pth.raw"
  PIXEL_MEAN: [104.0, 116.0, 124.0]
  RESNETS:
    DEPTH: 50
    RES2_OUT_CHANNELS: 256
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN-ReLU"
  RETINANET:
    NORM: "SyncBN"
  QUANTIZATION:
    scope: [
            # backbone
            'backbone',
            # Head
            'head',
           ]
    keyword: ["debug", "dorefa", "lsq"]
    fm_enable: True 
    wt_enable: True 
    padding_after_quant: True
    fm_bit: 3.0
    wt_bit: 3.0
    fm_boundary: 1.0
    wt_boundary: 1.0
    wt_quant_group: 1
    wt_adaptive: "var-mean"
    policy: 'configs/COCO-Detection/policy_retina-r50-fixpoint.txt'
SOLVER:
  BASE_LR: 0.001  # decrease by 10
OUTPUT_DIR: output/coco-detection/retinanet_R_50_FPN_1x-Full_SyncBN-FixFPN-FixPoint-lsq-M3F8L8
